module.exports = [
    "Cualquiera",
    "Alicante",
    "Almería",
    "Badajoz",
    "Barcelona",
    "Bilbao",
    "Burgos",
    "Cáceres",
    "Cádiz",
    "Córdoba",
    "Gerona",
    "Granada",
    "Guadalajara",
    "Huelva",
    "La Coruña",
    "Las Palmas de Gran Canaria",
    "Málaga",
    "Madrid",
    "Murcia",
    "Oviedo",
    "Pamplona",
    "Salamanca",
    "Santander",
    "Santa Cruz de Tenerife",
    "Segovia",
    "Sevilla",
    "Toledo",
    "Valencia",
    "Vigo",
    "Vitoria",
    "Zaragoza"
  ];