module.exports = [
    "Cualquiera",
    "Acústica",
    "Bachata",
    "Blues",
    "Bolero",
    "Bossa Nova",
    "Cantautor",
    "Clásica",
    "Country",
    "Cumbia",
    "Dance",
    "Dubstep",
    "Electrónica",
    "Experimental",
    "Flamenco",
    "Folk",
    "Funk",
    "Garaje",
    "Gospel",
    "Grunge",
    "Hip hop",
    "Indie",
    "Jazz",
    "Latino",
    "Merengue",
    "Metal",
    "New Age",
    "New Wave",
    "Pop",
    "Pop-rock",
    "Psicodelia",
    "Punk",
    "R&B",
    "Ranchera",
    "Rap",
    "Reggae",
    "Reggaeton (... ¿en serio? ¿No prefieres... qué se yo, montar Legos?)",
    "Rock",
    "Rockabilly",
    "Salsa",
    "Samba",
    "Ska",
    "Soul",
    "Swing"
];